version: '3.4'

services:
  log4dap:
    image: log4dap
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 1337:1337
      - 5005:5005
